# Generated by Django 5.2.5 on 2025-08-23 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0002_roleassignment_created_at_roleassignment_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('gtin', models.CharField(help_text='Global Trade Item Number (GTIN-14)', max_length=14, unique=True)),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('liquid', 'Liquid'), ('injection', 'Injection'), ('cream', 'Cream'), ('ointment', 'Ointment'), ('powder', 'Powder'), ('other', 'Other')], help_text='Physical form of the product', max_length=20)),
                ('strength', models.CharField(blank=True, help_text="Product strength (e.g., '500mg', '10ml')", max_length=100)),
                ('storage_temp_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum storage temperature in Celsius', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(100)])),
                ('storage_temp_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum storage temperature in Celsius', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(100)])),
                ('storage_humidity_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum storage humidity percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('storage_humidity_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum storage humidity percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('manufacturer', models.CharField(blank=True, help_text='Product manufacturer', max_length=255)),
                ('ndc', models.CharField(blank=True, help_text='National Drug Code (NDC)', max_length=11)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], default='active', help_text='Product status', max_length=20)),
                ('approval_number', models.CharField(blank=True, help_text='Regulatory approval number', max_length=100)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name', 'gtin'],
                'indexes': [models.Index(fields=['gtin'], name='supplychain_gtin_ed433c_idx'), models.Index(fields=['name'], name='supplychain_name_a5341d_idx'), models.Index(fields=['status'], name='supplychain_status_8f64bd_idx'), models.Index(fields=['manufacturer'], name='supplychain_manufac_49a14d_idx')],
            },
        ),
    ]
