# Generated by Django 5.2.5 on 2025-08-23 15:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lot_number', models.CharField(help_text='Unique lot number for this batch', max_length=100)),
                ('manufacturing_date', models.DateField(help_text='Date when the batch was manufactured')),
                ('expiry_date', models.DateField(help_text='Expiry date of the batch')),
                ('quantity_produced', models.PositiveIntegerField(help_text='Total quantity produced in this batch', validators=[django.core.validators.MinValueValidator(1)])),
                ('manufacturing_location', models.CharField(blank=True, help_text='Location where the batch was manufactured', max_length=255)),
                ('manufacturing_facility', models.CharField(blank=True, help_text='Facility or plant where the batch was manufactured', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('recalled', 'Recalled'), ('quarantined', 'Quarantined'), ('released', 'Released'), ('destroyed', 'Destroyed')], default='active', help_text='Current status of the batch', max_length=20)),
                ('quality_control_notes', models.TextField(blank=True, help_text='Quality control notes and observations')),
                ('quality_control_passed', models.BooleanField(default=True, help_text='Whether the batch passed quality control')),
                ('batch_size', models.CharField(blank=True, help_text="Size or volume of the batch (e.g., '1000 units', '500L')", max_length=100)),
                ('supplier_batch_number', models.CharField(blank=True, help_text="Supplier's batch number if different from lot number", max_length=100)),
                ('regulatory_approval_number', models.CharField(blank=True, help_text='Regulatory approval number for this batch', max_length=100)),
                ('certificate_of_analysis', models.CharField(blank=True, help_text='Certificate of Analysis reference', max_length=255)),
                ('product', models.ForeignKey(help_text='Product this batch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='supplychain.product')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['-manufacturing_date', 'lot_number'],
                'indexes': [models.Index(fields=['lot_number'], name='supplychain_lot_num_c43340_idx'), models.Index(fields=['product', 'lot_number'], name='supplychain_product_60b781_idx'), models.Index(fields=['manufacturing_date'], name='supplychain_manufac_754cf5_idx'), models.Index(fields=['expiry_date'], name='supplychain_expiry__6f13fb_idx'), models.Index(fields=['status'], name='supplychain_status_65c9c2_idx'), models.Index(fields=['manufacturing_location'], name='supplychain_manufac_59e305_idx')],
                'unique_together': {('product', 'lot_number')},
            },
        ),
    ]
