# Generated by Django 5.2.5 on 2025-08-23 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('supplychain', '0006_shipment_shipmentpack_shipment_packs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status Changed'), ('location_changed', 'Location Changed'), ('quality_check', 'Quality Check'), ('temperature_alert', 'Temperature Alert'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('recalled', 'Recalled'), ('inventory_count', 'Inventory Count'), ('maintenance', 'Maintenance'), ('calibration', 'Calibration'), ('user_action', 'User Action'), ('system_action', 'System Action'), ('alert', 'Alert'), ('warning', 'Warning'), ('error', 'Error'), ('other', 'Other')], help_text='Type of event that occurred', max_length=50)),
                ('entity_type', models.CharField(choices=[('product', 'Product'), ('batch', 'Batch'), ('pack', 'Pack'), ('shipment', 'Shipment'), ('user', 'User'), ('device', 'Device'), ('location', 'Location'), ('system', 'System')], help_text='Type of entity this event is associated with', max_length=50)),
                ('entity_id', models.PositiveIntegerField(help_text='ID of the entity this event is associated with')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the event occurred')),
                ('description', models.TextField(help_text='Human-readable description of the event')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event data in JSON format')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='info', help_text='Severity level of the event', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Location where the event occurred', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the event was triggered', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('system_info', models.JSONField(blank=True, default=dict, help_text='System information when the event occurred')),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the associated entity', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'supplychain_event',
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['timestamp'], name='supplychain_timesta_c196c1_idx'), models.Index(fields=['event_type'], name='supplychain_event_t_dfa511_idx'), models.Index(fields=['entity_type'], name='supplychain_entity__59dacb_idx'), models.Index(fields=['entity_id'], name='supplychain_entity__815e0e_idx'), models.Index(fields=['severity'], name='supplychain_severit_372ae5_idx'), models.Index(fields=['user'], name='supplychain_user_id_6d152a_idx'), models.Index(fields=['entity_type', 'entity_id'], name='supplychain_entity__04ae10_idx'), models.Index(fields=['event_type', 'timestamp'], name='supplychain_event_t_45c4f4_idx'), models.Index(fields=['severity', 'timestamp'], name='supplychain_severit_610389_idx')],
            },
        ),
    ]
