# Generated by Django 5.2.5 on 2025-08-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0007_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blockchain_block_number',
            field=models.PositiveBigIntegerField(blank=True, help_text='Block number where the event was anchored', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash for anchored event', max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of canonical event data', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='integrity_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('anchored', 'Anchored'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Status of blockchain anchoring', max_length=20),
        ),
    ]
