# Generated by Django 5.2.5 on 2025-09-07 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0008_event_blockchain_block_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Available quantity remaining in this batch', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
