# Generated by Django 5.2.5 on 2025-12-31 09:08

import django.core.validators
import supplychain.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0009_batch_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='lot_number',
            field=models.CharField(help_text='Unique lot number for this batch', max_length=100, validators=[supplychain.validators.validate_lot_number_format]),
        ),
        migrations.AlterField(
            model_name='pack',
            name='serial_number',
            field=models.CharField(help_text='Unique serial number for this pack', max_length=100, unique=True, validators=[supplychain.validators.validate_serial_number_format]),
        ),
        migrations.AlterField(
            model_name='product',
            name='gtin',
            field=models.CharField(help_text='Global Trade Item Number (GTIN-14)', max_length=14, unique=True, validators=[supplychain.validators.validate_gtin_format]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(help_text='Unique tracking number for this shipment', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_tracking_number', message='Tracking number must be 5-50 characters long and contain only letters, numbers, hyphens, and underscores.', regex='^[A-Za-z0-9_-]{5,50}$')]),
        ),
    ]
