# Generated by Django 5.2.5 on 2025-12-31 14:11

import django.db.models.deletion
import supplychain.models.document
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('supplychain', '0010_alter_batch_lot_number_alter_pack_serial_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(help_text='The ID of the entity this document is attached to')),
                ('file', models.FileField(help_text='The uploaded file', upload_to=supplychain.models.document.document_upload_path)),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the document')),
                ('category', models.CharField(choices=[('certificate', 'Certificate'), ('invoice', 'Invoice'), ('packing_list', 'Packing List'), ('shipping_label', 'Shipping Label'), ('coa', 'Certificate of Analysis'), ('msds', 'Material Safety Data Sheet'), ('quality_report', 'Quality Report'), ('photo', 'Photo'), ('other', 'Other')], db_index=True, default='other', help_text='Document category', max_length=50)),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('file_hash', models.CharField(blank=True, default='', help_text='SHA-256 hash of file content for integrity verification', max_length=64)),
                ('version_number', models.PositiveIntegerField(default=1, help_text='Version number of this document')),
                ('is_latest', models.BooleanField(db_index=True, default=True, help_text='Whether this is the latest version')),
                ('content_type', models.ForeignKey(help_text='The type of entity this document is attached to', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent_document', models.ForeignKey(blank=True, help_text='Parent document if this is a new version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='supplychain.document')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'supplychain_document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='supplychain_content_4fac55_idx'), models.Index(fields=['category'], name='supplychain_categor_7f01b2_idx'), models.Index(fields=['is_latest'], name='supplychain_is_late_436027_idx'), models.Index(fields=['uploaded_by'], name='supplychain_uploade_516e8c_idx')],
            },
        ),
    ]
