# Generated by coding agent

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0013_alter_event_entity_type_alter_event_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("batch_created", "Batch Created"),
                    ("batch_released", "Batch Released"),
                    ("batch_quarantined", "Batch Quarantined"),
                    ("batch_recalled", "Batch Recalled"),
                    ("quality_control_passed", "QC Passed"),
                    ("quality_control_failed", "QC Failed"),
                    ("shipment_created", "Shipment Created"),
                    ("shipment_dispatched", "Shipment Dispatched"),
                    ("shipment_in_transit", "Shipment In Transit"),
                    ("shipment_delayed", "Shipment Delayed"),
                    ("shipment_delivered", "Shipment Delivered"),
                    ("shipment_customs_cleared", "Shipment Customs Cleared"),
                    ("pack_commissioned", "Pack Commissioned"),
                    ("pack_aggregated", "Pack Aggregated"),
                    ("pack_disaggregated", "Pack Disaggregated"),
                    ("pack_decommissioned", "Pack Decommissioned"),
                    ("inventory_adjustment", "Inventory Adjustment"),
                    ("temperature_deviation", "Temperature Deviation"),
                    ("humidity_deviation", "Humidity Deviation"),
                    ("location_transfer", "Location Transfer"),
                    ("damage_reported", "Damage Reported"),
                    ("entity_created", "Entity Created"),
                    ("configuration_changed", "Configuration Changed"),
                    ("document_uploaded", "Document Uploaded"),
                    ("document_anchored", "Document Anchored"),
                ],
                help_text="Type of event that occurred",
                max_length=50,
            ),
        ),
    ]
